# Generated by Django 2.0 on 2018-01-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('college', models.CharField(max_length=64)),
                ('register_time', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
    ]
