# Generated by Django 2.0.1 on 2018-03-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_project', '0002_imagestorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_store_id', models.IntegerField()),
                ('tags', models.CharField(default='[]', max_length=512)),
            ],
        ),
    ]
